Separate check-condition job from create-release-branch in `create-release-pull-request.yml`

diff --git a/.github/workflows/create-release-pull-request.yml b/.github/workflows/create-release-pull-request.yml
--- a/.github/workflows/create-release-pull-request.yml
+++ b/.github/workflows/create-release-pull-request.yml
@@ -21,9 +21,26 @@ jobs:
       - name: Verify version string
         run: ./.github/tools/verify-semver.sh "${{ github.event.inputs.version }}"
 
+  check-condition:
+    name: Check condition before creating release branch
+    needs: verify-version
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v7
+        with:
+          ref: ${{ env.TARGET_BRANCH_NAME }}
+          fetch-depth: 0  # fetch all history for all tags and branches
+      - name: Check whether the release branch already exists
+        run: |
+          ! git branch --list --remotes | sed -e 's/^[[:space:]]*//' | grep -x origin/"${{ env.RELEASE_BRANCH_NAME }}" >/dev/null || {
+            echo "Error: branch \`${{ env.RELEASE_BRANCH_NAME }}\` already exists"
+            exit 1
+          }
+
   create-release-branch:
     name: Create release branch
-    needs: verify-version
+    needs: check-condition
     permissions:
       contents: write
       pull-requests: write
@@ -34,12 +51,6 @@ jobs:
         with:
           ref: ${{ env.TARGET_BRANCH_NAME }}
           fetch-depth: 0  # fetch all history for all tags and branches
-      - name: Check whether the release branch already exists
-        run: |
-          git branch --list --remotes | sed -e 's/^[[:space:]]*//' | grep -x origin/"${{ env.RELEASE_BRANCH_NAME }}" >/dev/null && {
-            echo "Error: branch \`${{ env.RELEASE_BRANCH_NAME }}\` already exists"
-            exit 1
-          }
       - name: Update package version in Cargo.toml
         run: |
           tmpfile=$(mktemp)
