Add check for existing release branch in `create-release-pull-request.yml`

diff --git a/.github/workflows/create-release-pull-request.yml b/.github/workflows/create-release-pull-request.yml
--- a/.github/workflows/create-release-pull-request.yml
+++ b/.github/workflows/create-release-pull-request.yml
@@ -34,6 +34,12 @@ jobs:
         with:
           ref: ${{ env.TARGET_BRANCH_NAME }}
           fetch-depth: 0  # fetch all history for all tags and branches
+      - name: Check whether the release branch already exists
+        run: |
+          git branch --list --remotes | sed -e 's/^[[:space:]]*//' | grep -x origin/"${{ env.RELEASE_BRANCH_NAME }}" >/dev/null && {
+            echo "Error: branch \`${{ env.RELEASE_BRANCH_NAME }}\` already exists"
+            exit 1
+          }
       - name: Update package version in Cargo.toml
         run: |
           tmpfile=$(mktemp)
